invite-codes:
  - abc123
  - def456

time-limit: 60 # in seconds
max-attempts: 3 # maximum number of failed attempts before punishment

punishment: ban-ip # ban, ban-ip or kick

kick-message: "&cYou must use /join <code> to play!"
ban-message: "&cYou are banned for too many failed /join attempts."
